modLoader="javafml"
loaderVersion="[47,)"
license="idk none"

[[mods]]
modId="blockblitz"
version="1.0"
displayName="Block Blitz"
credits="granderutai, just_oshiacute, raze2win, singulardud, superultra64"
displayURL="AGNAB's Amassing https://discord.gg/2JgqEMNfyr"
logoFile="logo.png"
authors="aetherepico"
description="adds buncha blocks"

[[dependencies.blockblitz]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




